author: Yakov Manshin
author_url: https://yakovmanshin.com/
clean: true
copyright: © 2020–2021 [Yakov Manshin](https://yakovmanshin.com/). Available under [Apache License v2](https://github.com/yakovmanshin/YMFF/blob/main/LICENSE).
custom_categories:
    - name: YMFF
      children:
          - FeatureFlag
          - FeatureFlagResolver
          - FeatureFlagResolverError
          - FeatureFlagResolverConfiguration
          - MutableFeatureFlagResolverConfiguration
          - TransparentFeatureFlagStore
          - RuntimeOverridesStore
          - UserDefaultsStore
    - name: YMFFProtocols
      children:
          - FeatureFlagKey
          - FeatureFlagResolverProtocol
          - FeatureFlagResolverConfigurationProtocol
          - FeatureFlagStore
          - FeatureFlagStoreProtocol
          - MutableFeatureFlagStoreProtocol
disable_search: true
github_file_prefix: https://github.com/yakovmanshin/YMFF/tree/main
github_url: https://github.com/yakovmanshin/YMFF
hide_documentation_coverage: true
title: YMFF v2 Docs
undocumented_text: Documentation Coming Soon…
