author: Yakov Manshin
author_url: https://me.ym.dev/
clean: true
copyright: © 2020–2022 [Yakov Manshin](https://me.ym.dev/). Available under [Apache License v2](https://github.com/yakovmanshin/YMFF/blob/main/LICENSE).
custom_categories:
    - name: YMFF
      children:
          - FeatureFlag
          - FeatureFlagValueTransformer
          - FeatureFlagResolver
          - FeatureFlagResolverError
          - FeatureFlagResolverConfiguration
          - MutableFeatureFlagResolverConfiguration
          - TransparentFeatureFlagStore
          - RuntimeOverridesStore
          - UserDefaultsStore
    - name: YMFFProtocols
      children:
          - FeatureFlagKey
          - FeatureFlagResolverProtocol
          - FeatureFlagResolverConfigurationProtocol
          - FeatureFlagStore
          - FeatureFlagStoreProtocol
          - MutableFeatureFlagStoreProtocol
disable_search: true
github_file_prefix: https://github.com/yakovmanshin/YMFF/tree/main
github_url: https://github.com/yakovmanshin/YMFF
hide_documentation_coverage: true
title: YMFF v3 Docs
undocumented_text: Documentation Coming Soon…
