#if !canImport(ObjectiveC)
import XCTest

extension FeatureFlagKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeatureFlagKeyTests = [
        ("testUniversalKeyInitializer", testUniversalKeyInitializer),
    ]
}

extension FeatureFlagResolverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeatureFlagResolverTests = [
        ("testIfValueIsOptional", testIfValueIsOptional),
        ("testIntValueResolution", testIntValueResolution),
        ("testNonexistentValueResolution", testNonexistentValueResolution),
        ("testOptionalIntNilValueResolution", testOptionalIntNilValueResolution),
        ("testOptionalIntNonNilValueResolution", testOptionalIntNonNilValueResolution),
        ("testOverrideValueValidationFailureOptional", testOverrideValueValidationFailureOptional),
        ("testOverrideValueValidationFailureTypeMismatch", testOverrideValueValidationFailureTypeMismatch),
        ("testOverrideValueValidationSuccess", testOverrideValueValidationSuccess),
        ("testRuntimeOverrideFailure", testRuntimeOverrideFailure),
        ("testRuntimeOverrideForNewKeys", testRuntimeOverrideForNewKeys),
        ("testRuntimeOverrideSuccess", testRuntimeOverrideSuccess),
        ("testStringValueResolution", testStringValueResolution),
        ("testValueRetrieval", testValueRetrieval),
        ("testValueTypeCasting", testValueTypeCasting),
        ("testValueTypeCastingFailure", testValueTypeCastingFailure),
        ("testValueTypeCastingSuccess", testValueTypeCastingSuccess),
        ("testValueValidation", testValueValidation),
    ]
}

extension FeatureFlagTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeatureFlagTests = [
        ("testBoolWrappedValue", testBoolWrappedValue),
        ("testIntWrappedValue", testIntWrappedValue),
        ("testNonexistentIntWrappedValue", testNonexistentIntWrappedValue),
        ("testNonexistentWrappedValueOverride", testNonexistentWrappedValueOverride),
        ("testOptionalIntValue", testOptionalIntValue),
        ("testStringWrappedValue", testStringWrappedValue),
        ("testWrappedValueOverride", testWrappedValueOverride),
    ]
}

extension RuntimeOverridesStoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RuntimeOverridesStoreTests = [
        ("testRuntimeOverride", testRuntimeOverride),
        ("testRuntimeOverrideRemoval", testRuntimeOverrideRemoval),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FeatureFlagKeyTests.__allTests__FeatureFlagKeyTests),
        testCase(FeatureFlagResolverTests.__allTests__FeatureFlagResolverTests),
        testCase(FeatureFlagTests.__allTests__FeatureFlagTests),
        testCase(RuntimeOverridesStoreTests.__allTests__RuntimeOverridesStoreTests),
    ]
}
#endif
