#if !canImport(ObjectiveC)
import XCTest

extension FeatureFlagKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeatureFlagKeyTests = [
        ("testUniversalKeyInitializer", testUniversalKeyInitializer),
    ]
}

extension FeatureFlagResolverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeatureFlagResolverTests = [
        ("testIfValueIsOptional", testIfValueIsOptional),
        ("testIntValueResolution", testIntValueResolution),
        ("testNonexistentValueResolution", testNonexistentValueResolution),
        ("testOptionalIntNilValueResolution", testOptionalIntNilValueResolution),
        ("testOptionalIntNonNilValueResolution", testOptionalIntNonNilValueResolution),
        ("testStringValueResolution", testStringValueResolution),
        ("testValueRetrieval", testValueRetrieval),
        ("testValueTypeCasting", testValueTypeCasting),
        ("testValueTypeCastingFailure", testValueTypeCastingFailure),
        ("testValueTypeCastingSuccess", testValueTypeCastingSuccess),
        ("testValueValidation", testValueValidation),
    ]
}

extension FeatureFlagTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeatureFlagTests = [
        ("testBoolWrappedValue", testBoolWrappedValue),
        ("testIntWrappedValue", testIntWrappedValue),
        ("testNonexistentIntWrappedValue", testNonexistentIntWrappedValue),
        ("testOptionalIntValue", testOptionalIntValue),
        ("testStringWrappedValue", testStringWrappedValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FeatureFlagKeyTests.__allTests__FeatureFlagKeyTests),
        testCase(FeatureFlagResolverTests.__allTests__FeatureFlagResolverTests),
        testCase(FeatureFlagTests.__allTests__FeatureFlagTests),
    ]
}
#endif
