name: Common Checks
on: [push]
jobs:
  spm_tests_macos:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_14.0.1.app
    - name: Run Tests
      run: swift test -v
  spm_tests_linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: swift test -v
  cocoapods-podspec-lint:
    runs-on: macOS-12
    needs: [spm_tests_macos, spm_tests_linux]
    steps:
    - uses: actions/checkout@v3
    - name: Lint Podspec
      run: pod lib lint --verbose
