name: Release
on:
  release:
    types: [published]
env:
  XCODE_PATH: "/Applications/Xcode_16.0.app"
jobs:
  run_common_checks:
    uses: ./.github/workflows/Common.yml
    with:
      force_all_checks: true
  cocoapods_trunk_push:
    name: Push to CocoaPods Trunk
    runs-on: macos-14
    needs: run_common_checks
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select -switch ${{ env.XCODE_PATH }}
    - name: Push
      run: |
        pod trunk push YMFF.podspec --verbose
