name: Run Tests
on: [pull_request, push]
jobs:
  spm-macos-test:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_13.4.app
    - name: Run tests
      run: swift test -v
  spm-linux-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test -v
  cocoapods-podspec-lint:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Lint Podspec
      run: pod lib lint --verbose
