name: Run Tests
on: [push]
jobs:
  spm-macos-test:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_14.0.1.app
    - name: Run tests
      run: swift test -v
  spm-linux-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test -v
  cocoapods-podspec-lint:
    runs-on: macOS-12
    needs: [spm-macos-test, spm-linux-test]
    steps:
    - uses: actions/checkout@v3
    - name: Lint Podspec
      run: pod lib lint --verbose
